### PR TITLE
Fix for dotnetcore not supporting setting option of linger state.

### PR DESCRIPTION
**Pull request by glmnet**

### CODE REVIEW

**Comment by Aimeast** [comment]
Hi, could you please squash 3 commits in 1 commit?

**Comment by glmnet** [comment]
I would If I knew how to do that. Isn't it an option you get when you use the Merge button? (Sorry no much experience with GitHub)

**Comment by Aimeast** [comment]
ref book, https://git-scm.com/book/en/v2/Git-Branching-Rebasing and https://help.github.com/articles/about-git-rebase/#commands-available-while-rebasing and https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

Please try and re-force push this PR.

**Comment by glmnet** [comment]
Thanks for the info, I didn't know one could do that. Do you think it is ok now?

**Pull request merged**
